### ISSUE TITLE
cadl init templates for emitter/library authors

### ISSUE THREAD

**Issue by nguerrera** [microsoft/typespec#1103]
It would be nice if you could use `cadl init` to get the basic structure of various kinds of cadl libraries.

**Comment by nguerrera** [comment]
This was suggested by a customer.

**Comment by timotheeguerin** [comment]
Does this mean populating the `main.cadl` with some sample code from the library?

**Comment by nguerrera** [comment]
The specific use case that came up was: "I'd like to write an emitter" and so you do `cadl init`, pick an emitter template and yes, there is some sample boilerplate filled in like a $onEmit stubbed out or with some sample code.

**Comment by nguerrera** [comment]
Updated issue title to clarify

**Comment by m-nash** [comment]
@nguerrera  I don't know if this is related so let me know if I should open this as a separate issue.

In the recent demo for `cadl compile .` which automatically generated multiple languages one of the improvements I think we need to make here is to define a application folder structure that makes sense.  As it sits now there is one output directory that is shared by all languages and each emitter / generator does something slightly different.

One option would be to have the compiler append the emitter name to the output-dir that is passed into it such that @azure-tools/cadl-csharp would get `[output-dir]/cadl-csharp`.  This would make the application folder structure look something like this

(Not exhaustive but just to show an example)
- main.cadl
- cadl-project.yaml
- package.json
  - cadl-csharp
    - MyProject.csproj
    - Generated
      - MyClient.cs
  - cadl-python
    - azure
      - mgmt
      - __init__.py
  - cadl-java
    - pom.xml
    - src
      - main

We would have cadl compile do this output directory concatenation so that customers could override this in their cadl-project.yaml per language they could change `cadl-csharp` to `dotnet` with this

```yaml
  "@azure-tools/cadl-csharp":
    "output-dir": "dotnet"
```
 
The emitter would simply use the output-dir that it gets from the compiler and only generate any sub structure that is needed.

**Comment by tjprescott** [comment]
@m-nash the issue you describe is separate and distinct from `cadl init`. Init is just supposed to bootstrap your cadl project structure. What you are describing is the structure of the ephemeral, non-tracked build folders. I'd recommend creating a separate issue.

**Comment by timotheeguerin** [comment]
We just added (in the last release) a convention that each emitter can define their own `output-dir` parameter which would take precedence over the compiler one. Would that not be enough? If you want to default to `{compilerOptions.outputDir}/cadl-csharp`  you should be able to do so.

**Comment by tjprescott** [comment]
Yes, that would work, but it would make more sense if every emitter didn't need to duplicate logic to support this. If the compiler simply supported the concept of `{compilerOptions.outputDir}/{emitter-name}` we would avoid all collisions and require no special emitter logic.

**Comment by timotheeguerin** [comment]
Actually added that a few month back
