### ISSUE TITLE
Should have the playground published to a fixed endpoint on release

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1150]
Right now the playground is an awesome tool for people to play with or report issue but it is always up to date with the main changes which result in some different behavior.

The playground was designed to work with bundled packages so I think we could just upload to `/<publihsed-version>/compiler.js` and similar for all the other versions.

**Comment by mikekistler** [comment]
@markcowl Could we bump this one up in priority. If we want to start using the playground for "live" examples as in my [typespec-openapi3-examples project](https://github.com/mikekistler/typespec-openapiv3-examples/blob/main/README.md), we need to have a stable version of TypeSpec and associated packages to target.

Currently any of these examples that do a `using OpenAPI`, which works fine in 0.48.0, fail in the playground because it already incorporates the namespace change to `TypeSpec.OpenAPI`.

**Comment by timotheeguerin** [comment]
This is done, playground currently use latest version instead of next, this issue tracks the version picker. https://github.com/microsoft/typespec/issues/2044
