### ISSUE TITLE
Removed deprecated versioning helpers

### ISSUE THREAD

**Issue by tjprescott** [microsoft/typespec#1424]
These versioning helpers have been deprecated and should be removed after 2 releases. See #1381 and #1361. These should be removed in the March release. 

**Deprecations for January release**
- getRenamedFromVersion
- getRenamedFromOldName
- renamedAfter
- getAddedOn
- getRemovedOn
- addedAfter
- removedOnOrBefore

**Comment by tjprescott** [comment]
@markcowl these should be removed in March, which is... the February sprint?
est: 1
pri: 0

**Comment by markcowl** [comment]
March == April Sprint

**Comment by markcowl** [comment]
Why did we deprecate these? - this essentially forces the use of projections for versioning and deprecates the usage pattern that is used for canonical spec code generation in cadl-providerhub-controller (and conceptually, other emitters which would prefer a canonical rather than individualloy versioned specs)

**Comment by tjprescott** [comment]
These were deprecated because these decorators can be applied multiple times, so the fact that these can only return a single value is incorrect and should not be relied upon.

**Comment by markcowl** [comment]
est: 1
