### ISSUE TITLE
Sidecar docs & example 

### ISSUE THREAD

**Issue by claudiababescu** [microsoft/typespec#1426]
Would it be possible to provide official documentation and examples of using a sidecar in CADL ?

**Comment by markcowl** [comment]
I think we are missing some user-focused documentation on this.  Essentially a sidecar is just an extra file that is included in a spec when you want to add metadata to a spec without changing the elements of the spec inline.  This could happen because the spec is written by one team and used for other purposes (like API documentation) by another team, or just to separate concerns or organize metadata to be more readable.

The main element of a sidecar file is the [augment decorator](https://microsoft.github.io/cadl/language-basics/decorators#augment-decorators) pattern.  This allows you to apply a decorator to an element that appears elsewhere in the spec, by using `@@` syntax and providing a reference to the decorator target.

For example
```cadl
model MyModel {
 myProperty: Foo;
}

// another cadl doc
@@doc(MyModel.myProperty, "The foo property of MyModel")
```

**Comment by markcowl** [comment]
ready for us to consider generic documentation for the sidecar pattern used by some emitters in public beta

**Comment by deyaaeldeen** [comment]
Working link for the augment decorators: https://microsoft.github.io/typespec/language-basics/decorators#augment-decorators
