### ISSUE TITLE
The operation does not carry the decorator defined for its namespace/interface when it is reference to other interface

### ISSUE THREAD

**Issue by chunyu3** [microsoft/typespec#1466]
Hi all

When we defined operation `one` in main.cadl, and reference in client.cadl as following:
main.cadl
```
namespace Azure.ClientAndOperationGroupService;

@autoRoute
namespace Alpha {​​
    #suppress "@azure-tools/cadl-azure-core/use-standard-operations" "This is test code."
    @action
    op one(): string;
}​​
```
client.cadl
```
@client({​​
  name: "NewOperationGroupService",
  service: Azure.ClientAndOperationGroupService
}​​)
interface NewOperationGroupService{​​
    oneFun is Azure.ClientAndOperationGroupService.Alpha.one;
}​​
```

The `@autoRoute` decorator will not pass-down to the operation `oneFun`. Is it the expected behavior?

**Comment by timotheeguerin** [comment]
This is by design(https://github.com/microsoft/cadl/issues/1335)  and is the same issue as #1420

What we don't have and we could maybe need is a `op myRename use externalOp` where it wouldn't be a copy but a reference to the operation so we'd look there for the information.

**Comment by markcowl** [comment]
Consolidating the issues here
- What is needed is a mechanism for reusing an operation, including its decoration
- This is likely mitigated by use of the azure.core operation templates, which should explicitly define autoRoute and operation path on the operations. Not sure that we should define a mechanism to make it easy to reshape APIs that do not use azure.core, or similar patterns that promote operation portability.
- Should be able to handle
  - reusing operations using @autoRoute - this may simply be that operations must use azure core operation templates
  - avoid redefining operation path with operation rename, again, use of azure core templates in the originals spec should fix this.
  - We should be able to carry over additional operation decoration from the spec, this is where the client definition

**Comment by daviwil** [comment]
To create SDK client definitions using sidecar files, we recommend that SDK teams pick out individual operations so that they can be renamed and/or annotated with additional decorators.

The problem with this approach is that the `op is` logic causes the decorators of the original operation to be re-executed on the new definition whichs changes the context of those decorators, often producing incorrect results.

The ideal outcome of referencing an original operation from the service specification to produce a modified client operation is this:

#### The route and other metadata of the original operation should be retained

An operation defined in the service specification should have the same route when redefined in the client specification with a new name or metadata attached.

This includes the name of the action which might be based on the original operation name as defined in the service spec.

## Possible Solutions

### Invent new syntax to reference original operation instead of defining a new one

This syntax should produce an `OperationReference` (new Cadl type) instead of an `Operation`:

```
namespace Azure.TestService {
  @autoRoute
  namespace Alpha {​​
      #suppress "@azure-tools/cadl-azure-core/use-standard-operations" "This is test code."
      @action
      op one(): string;
  }​​
}

namespace Azure.TestClient {
  @client({​​
    name: "TestService",
    service: Azure.TestService
  }​​)

  interface NewOperationGroupService{​​
      @doc("This is client-side documentation.")
      oneFun ref Azure.TestService.Alpha.one;
  }​​
}
```

The keyword can be `ref` or any other word that indicates that we're referring to an initial operation.  `alias` cannot work here because you can't apply new decorators to an alias.

I think it's possible to solve this problem without the need for new Cadl syntax and types, though.

### Provide a helper function that can return the original operation of another operation

This would require that SDK client generators be aware that they need to call this helper on any client operation to ensure they gather the appropriate metadata for the original operation defined in the service namespace.

In addition to requesting the original operation, it should be possible to query the route system to fetch the computed route for the original operation in context to where it was defined.  This should be possible by reusing existing logic in the routing system, we just need to expose it in a way that makes it easy to use.

For example:

```typescript
// Client generator code
// - clientNamespace is the namespace where the @client decorator is applied
// - serviceNamespace is the parameter to @client's `service` field

function getOriginalRoute(program: Program, clientOperation: Operation): string | undefined {
  const httpService = getHttpService(program, serviceNamespace);
  const originalOp = getOriginalOperation(program, clientOperation, serviceNamespace);
  if (originalOp) {
    return httpService.operations.find(sop => sop.operation === originalOp)?.path;
  }

  return undefined;
}
```

In this example, the proposed `getOriginalOperation` function is used to look up the original definition of the operation which `clientOperation` is derived from.  We pass the `serviceNamespace` to this function to ensure we don't pick up any intermediate operation definitions that are not defined inside of the service namespace.

This `getOriginalRoute` example can be provided by the HTTP library so that client generators don't need to write it themselves.

**Comment by tjprescott** [comment]
It seems that this PR is related: https://github.com/microsoft/cadl/pull/1576.

**Comment by daviwil** [comment]
## Alternate Proposal

### `OpReference<OriginalOperation>`

We will introduce a new operation signature in the `cadl-dpg` library called `OpReference<T>` (or `OperationReference<T>`) which represents a "soft reference" to an operation that is defined in the original service specification.  This operation signature will not be used directly, but instead client generators will call the function `getOperationReference` (or `getReferencedOperation`?) to see if an operation is returned and then use that one instead.

### `getOperationMetadata`

This is a higher-order function which accepts an operation (which could be an `OpReference<T>`) and a metadata accessor function to use for extracting metadata for the operation.  First, the function will try using the accessor function on the `OpReference` and if `undefined` is returned, will then execute the same metadata function on the original (referenced) operation.

The last parameter to this function, an options object, will enable the caller to skip the metadata lookup on the `OpReference` and go straight to the original operation.  This behavior is disabled by default because we'd prefer that they look for metadata on the `OpReference` first before looking at the referenced operation.

An example:

```cadl
@autoRoute
@service({ title: "Test Service"})
namespace Alpha {
  @test
  @doc("The original doc string.")
  @action op original(): string;
}

@client({
  name: "Test Client",
  service: Alpha
})

interface Beta {
  @test
  refOne is OpReference<Alpha.original>;

  @test
  @doc("The reference doc string.")
  refTwo is OpReference<Alpha.original>;
}
```

Here's an example that will extract the doc string from `refOne` and `refTwo`:

```typescript
getOperationMetadata(program, refOne, getDoc);   // -> "The original doc string."
getOperationMetadata(program, refTwo, getDoc);   // -> "The reference doc string."
getOperationMetadata(program, refTwo, getDoc, { originalOnly: true }), // -> "The original doc string."
```

### `getOperationRoute`

This is a special-case function for gathering the operation route for the original operation through an operation reference.  I propose that you would never want to get the operation route from the `OpReference` itself because it will always be wrong based on the rules of `route` and `autoRoute`.  Instead, the route should be pulled from the context of the original operation.

An example:

```cadl
@autoRoute
@service({ title: "Test Service"})
namespace Alpha {
  @test
  @action op one(): string;
}

@client({
  name: "Test Client",
  service: Alpha
})

interface Beta {
  @test
  oneClient is OpReference<Alpha.one>;
}
```

Here's an example that will extract the route for both `one` and `oneClient`:

```typescript
// Find the sole client
const clients = listClients(runner.context);

// Make sure the referenced operation is the same as the original
getOperationRoute(program, one, clients[0]);         // -> "/one"
getOperationRoute(program, oneClient, clients[0]);   // -> "/one"
```

**Comment by daviwil** [comment]
Fourth parameter should be a reducer-style function instead of an options bag.  Function should be given each of the operations and return the proper value.

**Comment by markcowl** [comment]
@m-nash Agreed to help with design

**Comment by daviwil** [comment]
A note about precalculating route values because @johanste and I have talked about this a few times now:

It would be nice if `autoRoute` routes could be precalculated as soon as the decorator is applied to an operation so that the stored route can then be carried across any future `op is` references.  This would sidestep the need for adding an indirection reference between client sidecar operations and their corresponding service operations.

I've looked at this once again and came to the conclusion that the lack of control over decorator execution order makes it impossible to do this reliably.  There's also the added wrinkle of the `RouteResolutionOptions` parameter that can be passed through `getHttpOperation` and friends; we can't predict what options a library or emitter will use when asking for operation routes, so there'sa good chance a precalculated route will get it wrong.

Since we can't precalculate routes reliably, the only other option is to move forward with operation reference indirection so that `@autoRoute` decorators don't get carried across to sidecar operations.  The downside of this approach is that it requires special handling by emitters to look up any operation metadata first on the referenced operation before looking at the sidecar operation.

**Comment by daviwil** [comment]
New possibility: write a linting rule that can detect when an `op is` is referring to a service operation which has containers with their own route fragments.  Calculate the full route and recommend that they apply `@route` directly on the operation, or perhaps replicate the route fragment on their interface.  Can we create a `routeOf` decorator in DPG that can simplify this?

**Comment by markcowl** [comment]
Create a linting rule to enforce

**Comment by markcowl** [comment]
@daviwil Can we create an issue for the linting rule here?

**Comment by daviwil** [comment]
Filed issue https://github.com/Azure/typespec-azure/issues/3333 for the linting rule that we need to guard against this problem.
