### ISSUE TITLE
Update OpenAPI3 emitter to support new collectionFormat in http decorators

### ISSUE THREAD

**Issue by markcowl** [microsoft/typespec#1711]
Dependent on: https://github.com/microsoft/typespec/issues/1710

- [ ] Support 'csv', 'tsv', 'ssv', 'pipes', 'multi' formats for `@query` and `@header`
- [ ] Add tests including each format

**Comment by markcowl** [comment]
est: 3

**Comment by darrelmiller** [comment]
Can I make the request that you use the terms "simple" and "form" as per RFC 6570 https://www.rfc-editor.org/rfc/rfc6570#section-3.2.2 instead of "csv" and "multi" and make "simple" the default?  This will also align with OpenAPI v3/v3.1 https://spec.openapis.org/oas/latest.html#style-values

This approach also gives a standards based solution to serializing parameters that are dictionaries and single depth objects., if you want to do that in the future.

**Comment by johanste** [comment]
While I personally don't find the RFC 6570 terminology self explanatory, I do support - at the very least - allowing the names as synonyms of the corresponding openapi 2 terminology. I really don't have a strong opinion on deprecating the openapi 2 terminology, but we'd have to keep the existing terms for at least a couple of releases.

**Comment by tjprescott** [comment]
It doesn't appear that OpenAPI3 supports "tsv":
https://github.com/OAI/OpenAPI-Specification/blob/3.0.3/versions/3.0.2.md#style-values

**Comment by markcowl** [comment]
@tjprescott  I think the only way we could tupport tsv would be through an extension, so a warning and defaulting to simple seems like the right thing.

I think we can add 'simple' and 'form' to the list of values.  We might later think of deprecating csv and multi.
