### ISSUE TITLE
Improve type check error message for nested values

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1823]
Right now we have a pretty basic message that say the top level type is not assignable to the target. But it would be nice to be able to dig into why(which property doesn't match) as well as trying to show the error at the deepest location possible.

For example here show it on` format: `
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwpvcCBmb28oCiAgQHF1ZXJ5xVwgIGZvcm1hdDogImJhZMVUfSkKICBiYWQ6IHN0cmluZ1tdCik6IHZvaWQ7Cg%3D%3D)

**Comment by markcowl** [comment]
epic: tooling

**Comment by markcowl** [comment]
Another example:

When you use a decorator that has an anonymous object shape as one of its parameter types, the error produced by the compiler makes it very unclear what went wrong.  For example:

```
import "@typespec/http";
using TypeSpec.Http;

@route("foo", { shared: "foo" })
op go(): {};
```

[Playground](https://cadlplayground.z22.web.core.windows.net/prs/1798/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CnVzaW5nIFR5cGVTcGVjLkh0dHA7CgpAcm91dGUoImZvbyIsIHsgc2hhcmVkOiDFESB9KQpvcCBnbygpOiB7fTs%3D)

The error returned is:

```
error invalid-argument: Argument '(anonymous model)' is not assignable to parameter of type '(anonymous model)'
```

It'd be nice if it could print out the expected shape at least so that the user has a lead on what they need to fix.

**Comment by timotheeguerin** [comment]
This was improved in https://github.com/microsoft/typespec/pull/4357
