### ISSUE TITLE
Increase minimum Node version to 18

### ISSUE THREAD

**Issue by mikeharder** [microsoft/typespec#1847]
The minimum Node version of all packages should be increased from 16 to 18, in part to allow us to use APIs only in Node 18 like `fetch`. (https://github.com/microsoft/typespec/issues/1846).

https://github.com/microsoft/typespec/blob/a5d648c95699ab4f6220f8adc17a30102b0ae386/packages/compiler/package.json#L47

**Comment by timotheeguerin** [comment]
Node 16 has now reached EOL as of today. https://nodejs.org/en/blog/announcements/nodejs16-eol

So we should schedule this, there is nothing urgent right now but dependencies might start to stop working on node 16 and/or setup their own engine requirement.

**Comment by markcowl** [comment]
est: 3

**Comment by markcowl** [comment]
**Describe the breaking change**
Node version 16 is out of support, remove nofe16 from node engine versions in package.json,  consumers should end usage of node 16 (otherwise, warning)

**Back-compat design to avoid immediate breaking**
Any back-compat design: Verified with DPG team no node16 usage in pipelines

**Link to detailed breaking design**

**Impact**
This change affecting:

- [ ] ARM
- [ ] Data-plane
- [ ] Existing specs: approx. # of service/spec impacted
- [x] New specs
- [x] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: November

**Additional information**
