### ISSUE TITLE
Do we need `@resourceTypeForKeyParam` decorator

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#1981]
Can't seem to find use for it.

**Comment by markcowl** [comment]
SHould this be moved to private namespace, or deprecated/removed?

**Comment by markcowl** [comment]
est: 5

**Comment by daviwil** [comment]
It's being used in `typespec-azure-resource-manager` here:

https://github.com/Azure/typespec-azure/blob/e449b4081581c58ce3e6c8583afdbb78c99b0ec7/packages/typespec-azure-resource-manager/src/namespace.ts#L96

We can definitely make the decorator private-ish though, because it's really only meant to be used internally to the REST library.

**Comment by markcowl** [comment]
**Describe the breaking change**

The internal `@resourceTypeForKeyParam` decorator is moving to a provate namespace to discourage any usage outside our libraries

**Back-compat design to avoid immediate breaking**
None:  No specs are using this decorator

**Link to detailed breaking design**

**Impact**
This change affecting:

- [ ] ARM
- [ ] Data-plane
- [ ] Existing specs: approx. # of service/spec impacted 
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: July 2023

**Additional information**
Add any other information about the change including fixes for here.
