### ISSUE TITLE
IDE: Intellisense should restrict the list of choices by language feature

### ISSUE THREAD

**Issue by garethj-msft** [microsoft/typespec#2081]
Intellisense should curtail the list of names presented to ones semantically applicable to the syntax.
e.g. extending interfaces should only show other interfaces
extending models should only show other models.

This will help new users especially learn productively.

Example
Type the following
interface Foo extends[ctrl-spacebar]

Expected behavior:
list of interface types that can be extended

Actual behavior:
List of a much larger set of identifiers in scope including models and namespaces - pick a random one and then get a compiler error.

**Comment by nguerrera** [comment]
Just to help whoever works on this, we do have some refinement/restriction like this today. For example, `using |` will only offer namespaces. And `@|` will only offer decorators and namespaces.

See https://github.com/microsoft/typespec/blob/c37d1c60bc54202c87b9f2b9fed075273636b84b/packages/compiler/src/core/checker.ts#L1971

**Comment by markcowl** [comment]
@nguerrera list of tasks to implement

**Comment by nguerrera** [comment]
Candidates I've found so far, including those that are already done to have the list in one place.

- [x] using only namespace
- [x] `@` or `@@` only decorator
- [ ] scalar extends only scalar
- [ ] interface extends only interface
- [ ] spread into model only model
- [ ] spread into enum only enum
- [ ] model is only model
- [ ] operation is only operation
- [ ] intersect only models
- [ ] template argument only if constraint is satisfied
- [ ] decorator arg only if parameter type is satisfied

NOTE: In all of these, we must always always also include namespaces in completions since user may be trying to qualify by namespace where the completion goes. So "only scalar", for example, above is really "only scalar or namespace".

I'm also not entirely sure if all of these are worthwhile. There is a trade-off that I see. We're completing in incomplete code and maybe the user wants to complete something, then fix the error by changing something else. In some cases, this could sort of enforce making edits to express yourself in a particular order to get full benefit of completion. And even if not, it could actually be less confusing to let the user pick something they expect to see and thought would work and then get a chance to read the error message that explains why it won't work. It may be worth evaluating this trade-off for each of these. I'm not sure it applies equally to all of them.

It's also worth noting that other languages don't do this everywhere they theoretically could.

Here's an example using C# in VS 2022 that's directly analogous to the motivating example here.

<img width="320" alt="image" src="https://github.com/microsoft/typespec/assets/75470/92b28bd1-2693-4400-82de-ed303d8d8429">

We're offered to make an interface extends a class in C# even though that is invalid. 

For bonus consideration, we're offered another mistake to make the interface extend itself.

**Comment by nguerrera** [comment]
Unassigning and moving to backlog now that we have this list.

**Comment by mzhongl524** [comment]
This issue has been resolved
