### ISSUE TITLE
[Feature Request] support array of arguments with `--option` of `tsp compile`

### ISSUE THREAD

**Issue by msyyc** [microsoft/typespec#2092]
I add global flag `--skip-special-headers` in emitter which receives array of args. Here is my definition in emitter:

[add `--skip-special-headers` by msyyc · Pull Request #1975 · Azure/autorest.python (github.com)](https://github.com/Azure/autorest.python/pull/1975/files#diff-8b83f3e2ddb57a306b4831fc4649255e0933831405c6b1b0e102399a6b678314)

However, I don't know how to set it with cmd line when writing test. I tried several ways:

(1) `... --option @azure-tools/typespec-python.skip-special-headers='client-request-id' --option @azure-tools/typespec-python.skip-special-headers='if-match'`

(2) `... --option @azure-tools/typespec-python.skip-special-headers='client-request-id,if-match'`

But all of them reports the following error:
![image](https://github.com/microsoft/typespec/assets/70930885/fdecb491-07dc-4c7d-91cc-7d6800924c77)

I hope compiler could provide a way to permit emitter set an option to receive array of arguments by cmd line.

**Comment by daviwil** [comment]
## Proposed Design

### Use delimiters for array values

This will be the clearest option despite the need for delimiter escaping in some cases.  I'll explain why using the same option name multiple times is problematic in just a bit.

If we use delimiters:

- First of all, what delimiter to use?  `,` `;` `|` etc
- Use backslash `\` for escaping?  Grave `\`` ?
- Emitter's option schema can specify that the option be either a string *or* an array of strings
- If the emitter's value schema enforces that the option *must* be an array, we can support using the delimiter at the end of the option value to indicate that it is an array despite only being a single value

For example:

```
--option my-emitter.foo='one,two,three'
```

Or for a single value forced to be an array:

```
--option my-emitter.foo='one,'
```

An example option schema:

```javascript
const EmitterOptionsSchema: JSONSchemaType<MyEmitterOptions> = {
    type: "object",
    additionalProperties: true,
    properties: {
      "foo": { type: "array", items: { type: "string" }, nullable: true },
    },
    required: [],
};
```

**NOTE:** At the time of option parsing, we don't know what the emitter's schema is so we can't make assumptions about the specific option's value type, thus we must implement clear behavior and let the JSON schema validator take care of reporting nonconforming values.

#### Why not multiple `--option` for array?

Example:

```
--option @azure-tools/typespec-python.skip-special-headers='client-request-id' --option @azure-tools/typespec-python.skip-special-headers='if-match'
```

- Extremely verbose, might hit some kind of command length limit with many array values for one option
- Not really clear that this usage pattern will aggregate the values into an array
- Doesn't enable you to override the same emitter option with a later CLI arg

### Option overrides with array values

Currently, CLI option values are parsed to extract the key/value pair which may include an emitter name.  The value part of the option always overrides what may already be there for the same key.

To maintain the same ability to override values at CLI, we should not try to aggregate list values of the same key, otherwise we will need to switch to always aggregate to avoid weird behavior in cases like this:

```
--option my-emitter.foo='one' --option my-emitter.foo='two' --option my-emitter.foo='three,four,five'
```

If we switch to aggregation the first time we see an array value but override until then, the final option value would be `["two", "three", "four", "five"]` because the `"one"` value would be overridden.

Thus, it's better to be extra clear and *always* override if the same option key is used more than once.

The same approach should be applied to overriding of options coming from `tspconfig.yaml` files.

### Should we enable opt-in aggregation for array merges?

Do we think an emitter author would ever want to aggregate (and not override) array values across emitter options and CLI?

For example, the `tspconfig` might contain:

```yaml
options:
  "my-emitter":
    foo:
    - "one"
    - "two"
```

And the CLI arguments might contain:

```
--option my-emitter.foo='three,four,five'
```

Would we ever want to aggregate all of these values together into a single array?

If so, how would we express that?  Probably can't be at the JSON schema level

Special syntax on defined option name?  Like `my-emitter.foo+`, the `+` at the end indicating an aggregating option?  (Not so great)

Other options?

**Comment by bterlson** [comment]
Notes:

* The future is using TypeSpec instead of JSON Schema, may be opportunities to drive better CLI parsing.
* Can we perhaps just pass through string arguments to the emitter and let it handle it? It's possible, though maybe some downsides (e.g. consistency of command line args, every emitter implementing splitter logic).
* Type-directed arg parsing would allow us to use the option schema to interpret the CLI command more rigorously, passing emitters scalars or arrays as necessary.
* Possibly be consistent with yargs/azd? Spaces for separate args.

Preferences:

* Preference for handling this in the compiler as opposed to passing through to emitters and having them parse it.
* Preference for string-with-commas: `--option my-emitter.foo="three,four,five"`.
* Later, express options in TypeSpec, support aggregation, etc.

**Comment by daviwil** [comment]
Implementation issue is https://github.com/microsoft/typespec/issues/2404.
