### ISSUE TITLE
Invalid metatype property references do not raise an error

### ISSUE THREAD

**Issue by johanste** [microsoft/typespec#2163]
```typespec
import "@typespec/http";

@TypeSpec.Http.get op Read<T extends TypeSpec.Reflection.Model>(... T): T;

@TypeSpec.Http.head op Head<TOp extends TypeSpec.Reflection.Operation>(... TOp::thisProbablyShouldntWork): void;


model Smurf {
  @key
  @TypeSpec.Http.path id: string;
  something: string;
}

op readSmurf is Read<Smurf>;
op headSmurf is Head<readSmurf>;
```

doesn't trigger an error for the `TOp::thisProbablyShouldntWork` model spread...

[Playground](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CgpAVHlwZVNwZWMuSHR0cC5nZXQgb3AgUmVhZDxUIGV4dGVuZHMgySRSZWZsZWN0aW9uLk1vZGVsPiguLi4gVCk6IFTSTGhlYWTETUjFTU9w3U9PcGVyYcQKx1NPcDo6dGhpc1Byb2JhYmx5U2hvdWxkbnRXb3JrKTogdm9pZDsKCgpt5ACGIFNtdXJmIHsKICBAa2V5xAfuAIpwYXRoIGlkOiBzdHJpbmc7CiAgc29tZXRoaW5nyhV9CgpvcCByZWFkxlBpc%2BYBCMUOPjvEHeQA08kd5QDYyS8%2BOwo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by bterlson** [comment]
I believe this is the [min repro](https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=bW9kZWwgQSB7fQrGC0IgeyAuLi4gQTo6dGVzdCB9&e=%40typespec%2Fopenapi3&options=%7B%7D).

```
model A {}
model B { ... A::test }
```

**Comment by markcowl** [comment]
## Breaking Change Review
**Describe the breaking change**

Invalid references to type metadata in API Specs will now produce an error, instead of being silently ignored.  If there are any existing specs that use invalid type reference metadata, these will now fail compilation with an error diagnostic

```typespec
import "@typespec/http";

@TypeSpec.Http.get op Read<T extends TypeSpec.Reflection.Model>(... T): T;

@TypeSpec.Http.head op Head<TOp extends TypeSpec.Reflection.Operation>(... TOp::thisProbablyShouldntWork): void;

```

**Back-compat design to avoid immediate breaking**
Any back-compat design: None

**Impact**
This change affecting:

- [ ] ARM
- [ ] Data-plane
- [x] Existing specs: 0
- [ ] New specs
- [ ] Emitters
- [ ] SDK

**Targeted Sprint**
Sprint: August (release: 8/8)

**Additional information**
