### ISSUE TITLE
Compiler error on REST import

### ISSUE THREAD

**Issue by maggiepint** [microsoft/typespec#2226]
I have the following TypeSpec code in my `main.tsp`

```
import "@typespec/http";
import "@typespec/rest";
import "./models/project.tsp";

@service({
  title: "Stanza Management",
  version: "1",
})
namespace StanzaManagement;

using TypeSpec.Http;
using TypeSpec.Rest;
using Project;

@error
model Error {
  code: int32;
  message: string;
  meta: unknown;
}
```

Since I suspect it may matter, the following is the contents of `models/project.tsp`

```
model Project {
  name: string;
  id?: string | null;
  stanzaCustomerId?: string | null;
  environmentIds?: string[] | null;
}
```

When I run `tsp compile .` from the main directory, I get the following:

```
TypeSpec compiler v0.46.0

Internal compiler error!
File issue at https://github.com/microsoft/typespec

TypeError: Cannot read properties of undefined (reading 'values')
    at addUsingSymbols (file:///Users/maggiejohnson-pint/code/chorus/api/spec/node_modules/@typespec/compiler/src/core/checker.ts:516:39)
    at setUsingsForFile (file:///Users/maggiejohnson-pint/code/chorus/api/spec/node_modules/@typespec/compiler/src/core/checker.ts:457:7)
    at createChecker (file:///Users/maggiejohnson-pint/code/chorus/api/spec/node_modules/@typespec/compiler/src/core/checker.ts:327:5)
    at compile (file:///Users/maggiejohnson-pint/code/chorus/api/spec/node_modules/@typespec/compiler/src/core/program.ts:366:21)
    at Object.handler (file:///Users/maggiejohnson-pint/code/chorus/api/spec/node_modules/@typespec/compiler/src/core/cli/cli.ts:143:25)
```

This seemed to happen when I added REST instead of using HTTP and moved a couple other things around. I'm sure I can find a way to walk backwards, but wanted to follow the directions and file. All typespec dependencies, not just the compiler, appear to be `0.46.0` in the lockfile.

**Comment by maggiepint** [comment]
This goes away when I remove the `using Project` and instead tells me I have no routes exposed. Put that there because I was experimenting with how REST generation worked - it's not entirely clear how to use from a separate file in the examples.

**Comment by maggiepint** [comment]
This code works - took me a second to realize you needed to declare the interface even if it was empty/didn't have custom route overrides. Makes sense though.

```
import "@typespec/http";
import "@typespec/rest";
import "@typespec/openapi3";
import "./models";


@service({
  title: "Stanza Management",
  version: "1",
})
namespace StanzaManagement;

using TypeSpec.Http;
using TypeSpec.Rest;

@error
model Error {
  code: int32;
  message: string;
  meta: unknown;
}

interface ProjectService extends Resource.ResourceOperations<Project, Error> {
}
```

**Comment by mikekistler** [comment]
Thanks for reporting this! Here's a recreate in the playground that shows the compiler exception.

[Playground example](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKQHNlcnZpY2UoewogIHRpdGxlOiAiV2lkZ2V0IFPGGyIsCiAgdmVyc2lvbjogIjEuMC4wIiwKfSkKbmFtZXNwYWNlIERlbW%2FHLzsKCm1vZGVsIMdGxFlAdmlzaWJpbGl0eSgicmVhZCIsICJ1cGRhdGUiKcQgcGF0aAogIGlkOiBzdHJpbmc7CgogIHdlaWdodDogaW50MzI7CiAgY29sb3I6ICJyZWQiIHwgImJsdWUiOwp96ADexnPkANdlcnJvcucAiUXEDOUAiGNvZGXLT21lc3NhZ2XKdH0KCkByb3V0ZSgiL3fFTHMiKQpAdGFnKOcBFcQQaW50ZXJm5AD3xxTFXEDkAO1saXN0KCk6xxlbXSB8xn7EbsUh5AD9KOUA7%2BsA7ckxzS9wb3N0IGNyZWF0ZSguLi7GItcrYXRjaCDmAVHfLEBkZWxldGUgxgf0AIt2b2lkzTLnARJ7aWR9L2FuYWx5emUiKecAoMcQ1EjGCcpKfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

A "using" on a model name isn't valid, but the compiler should not crash because of it.

**Comment by timotheeguerin** [comment]
[minimal playground repro](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgV2lkZ2V0IHt9Cgp1c2luZ8cROwo%3D&e=@typespec/openapi3&options=%7B%7D)

**Comment by markcowl** [comment]
Fix the crashes with an appropriate diagnostics
