### ISSUE TITLE
`model is` of a model with `@friendlyName` use the friendlyName instead of the model name

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2276]
```tsp
@friendlyName("Foo{name}", T)
model Foo<T> {
  t: T;
}

model Bar is Foo<string> {}
```

I would expect to have a model named `Bar` not `Foostring`

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=QGZyaWVuZGx5TmFtZSgiRm9ve25hbWV9IiwgVCkKbW9kZWwgRm9vPFQ%2BIHsKICB0OiBUOwp9CscaQmFyIGlzxSFzdHJpbmc%2BIHt9&e=%40typespec%2Fopenapi3&options=%7B%7D)

I think to solve this we need to make it so that calling `getFriendlyName` on a non template instance should be ignored.

**Comment by tjprescott** [comment]
# `@friendlyName` design

## Current Behavior

### Compiler
Currently, the behavior of `@friendlyName` is completely open to interpretation by emitters. The compiler doesn't constrain it's use and thus it can be applied to any type, templated or otherwise. This has the unfortunate side effect that it often does nothing when used where one might reasonably expect it to (for example, on operations or property names).

### `typespec-azure-core`
Contains a rule that using `@friendlyName` on anything other than an operation, model, interface or union is a warning. This was a rule migrated from TCGC. However, even with the warning in place, the behavior flows through to other emitters and thus still has an effect.

### `typespec-autorest`, `openapi3`
Both of these emitters simply call `getFriendlyName` and, if there is one, they apply it for type names.

### `typespec-providerhub-controller`
Likewise, this looks _first_ for a friendly name on a type and uses that, regardless of whether the referenced `Type` is templated or not.

## Option 1: Constrain to templated use only in compiler

If we change the signature, this will require changes to `typespec-autorest`, `openapi3` and `typespec-providerhub-controller`. It's also a breaking change. 

## Option 2: Add linter rule warning in compiler and change behavior of emitters

We could move the rule from `typespec-azure-core` to the `compiler` and change the behavior of emitters to "do nothing" in the non-templated cases. This would also be a breaking change since the behavior of any existing usages would change.

## Option 3: Add linter rule warning in compiler and don't change behavior of emitters

As in option 2, we move the rule up into the compiler, but we leave the current emitter behaviors as-is in regards to `@friendlyName`. This is the _least_ breaking change, since it would merely require existing specs that rely on this behavior to suppress the warning, but would still be considered breaking.

**Comment by timotheeguerin** [comment]
Option 4: 
Make a new decorator with a better name for what this was intended to be `@instanceName` or whatever else. And that will only work on template declaration.

**Comment by tjprescott** [comment]
I will promote Option 4 to option 1 since I think it's probably the most logical path forward.

**Comment by tjprescott** [comment]
Another option...

1. Leave `@friendlyName` in the compiler (or deprecate it)
2. Update `typespec-autorest`, `typespec-providerhub-controller` and `openapi3` to either no longer use `@friendlyName` or add rules to warn against using `@friendlyName`.
3. Defer to emitters or libraries like TCGC to resolve the issue of anonymous model names (i.e. no replacement for `@friendlyName` in azure core or compiler)

**Comment by timotheeguerin** [comment]
# Proposal

## Problem

- Confusing name
- Carries over to `model is` preventing to specify a custom name without reusing `@friendlyName`

## Solution

1. deprecate/remove
3. Introduce `@templateInstanceName` decorator to fit the purpose friendlyName was made

That decorator will only be allowed to be defined on a template. And it will only set the data on the template it is defined on. It will not carry over with `model is`(Cheat on the decorator application behavior - possible by comparing the decorator node and target node)

```tsp
@templateInstanceName("Foo{name}", T)
model Foo<T> {

}

alias Case1 = Foo<string>; // Foostring is the name given by getTemplateInstanceName();

model Case2 is Foo<string>; // undefined is the name given by getTemplateInstanceName() so we use Case2


model Baz<T> is Foo<T>;

@templateInstanceName("WithOverride{name}", T)
model WithOverride<T> is Foo<T>;


alias Case3 = Baz<string>; // This has no name given
alias Case4 = WithOverride<string>; // WithOverride is the name given by getTemplateInstanceName()
```

## `@encodedName`, `@clientName`, `@templateInstanceName` when to use what?

- `@encodedName` purpose is to give a different name when serializing to a specific media type. (e.g. `application/json`)
- `@clientName` purpose is to give a different name for a specific emitter/client
- `@templateInstanceName` purpose is only to give a default name for a template instance. If a user wants a different name they can use `model is` to give a different name.

- `@projectedName` - Deprecated
- `@friendlyName` - Deprecated

**Comment by timotheeguerin** [comment]
Problems: 
- Could this be combined with `@clientName` in someway
