### ISSUE TITLE
should report error if specify @ query in the response ? 

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#2477]
Should we allow @ query in the response alias defintion ? 
In this example [typespec playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKICB2ZXJzaW9uOiAiMS4wLjAiLAp9KQpuYW1lc3BhY2UgRGVtb8cvOwoKYWxpYXMgx0Y9IMRbQHZpc2liaWxpdHkoInJlYWQiLCAidXBkYXRlIinEIHBhdGgKICBpZDogc3RyaW5nOwoKICB3ZWlnaHQ6IGludDMyOwogIGNvbG9yOiAicmVkIiB8ICJibHVl5ADdICBAcXVlcnnkAMZlc3TKRX07CgpAZXJyb3IKbW9kZWwgRcQM5QCUY29kZctbbWVzc2FnZcs7CgpAcm91dGUoIi935QDNcyIpCkB0YWco5wEjxBBpbnRlcmbkAQXHFMVcQOQA%2B%2BQA6CjlANrrANgpOscpIHzmAIzEfEBwb3N0IGNyZWF0ZSguLi7GItMrfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D), we have a @ query test in the response alias definition, And the OAI3 generated response type take test as a property of the alias model in the body.  I guess this is not expected ? 

The same thing happens if we have a @ query in the model definition.

**Comment by qiaozha** [comment]
Maybe also consider @ path being used in response ?

**Comment by bterlson** [comment]
These are deliberately allowed to occur in order to allow for reusing the same model for input and output contexts, e.g. when a type is created, an id is passed in the path, but when read, it is just part of the body. You can read more about this [here](https://microsoft.github.io/typespec/standard-library/http/operations#metadata).

**Comment by qiaozha** [comment]
oh interesting. Thanks for sharing the background with me 😊 
I just have one question, should we allow path and query parameters in response defintion out side of the response model ? 
something like 
` @get read(@path id: string): {...Widget, @query queryParam: string, @path pathParam: string} | Error;`

**Comment by bterlson** [comment]
There isn't a point to writing something like that (the metadata will always be inapplicable), but I'm not sure it's worth investing in making it an error. It is only an error when you have the knowledge about how it was lexically written (inline in the response), but from the evaluated typespec perspective (where linters/emitters work) we don't know that the user wrote it that way, maybe that metadata was spread in from some reusable component or whatever.

**Comment by qiaozha** [comment]
I have rephrased my words as "should we allow path and query parameters in response defintion outside of the request model ?"

**Comment by weidongxu-microsoft** [comment]
@bterlson 

A `@path` property could be ambiguous.
But a worse item is `@query` property. It is 99% wrong if it appears in a response and treated as a property of response body.
https://github.com/Azure/cadl-ranch/issues/487#issuecomment-1878239251

One alternative would be to lint warning if `@path` or `@query` appears in response model?

It is very risky to allow `@query` (or `@path`) property appear in response body. Removing a property in response body would be considered a breaking change, even that is caused by an oversight on typespec or typespec-autorest.

**Comment by bterlson** [comment]
Path and query seem same-ish to me - sometimes you want to serialize parts of a model as a path or query if available, otherwise they are part of the data model. I definitely agree for queries it is less common to want this, but disallowing this for path seems clearly not good to me. And I'm not sure I would want to treat query differently.

I don't understand the risk yet, but if Azure wants to make such things a lint error I won't object. Just note that this will require creating separate models for inputs and outputs which may or may not be desirable.

**Comment by weidongxu-microsoft** [comment]
Agree that `@path` could be ambiguous. It does make sense that there are cases that service do have it in path and in response body.

For the DevBox case, their dev attempts this
```
model DevBox {
  @key("projectName")
  @visibility("read", "create")
  @doc("Name of the project this Dev Box belongs to")
  @segment("projects")
  @path
  projectName: string;

  @doc("The AAD object id of the user this Dev Box is assigned to.")
  @visibility("read", "create")
  @projectedName("csharp", "userId")
  @projectedName("java", "userId")
  @segment("users")
  @path
  userId: Azure.Core.uuid;

  @doc("Display name for the Dev Box")
  @visibility("read", "create")
  @segment("devboxes")
  @path
  devBoxName: string;

  ...
}
```
https://github.com/Azure/azure-rest-api-specs/blob/7079bc14ba643dd7e926228cb13b7e7868d0b0f2/specification/devcenter/DevCenter/devbox/models.tsp#L304C1-L332C20

While personally I'd recommend `@resource` and `@parentResource` for the model and segments (it still a single `DevBox` model, but it now be apparent that `projectName` and `user` is on body as readonly).
```
@resource("box")
@parentResource(User)
model DevBox {
  @key @visibility("read")
  devBoxName: string;

  @visibility("read")
  projectName: string;

  @visibility("read")
  user: string;

  ...
}
```
https://cadlplayground.z22.web.core.windows.net/cadl-azure/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdMwZYXp1cmUtdG9vbHMvyCUtxhVjb3JlIjsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN00RVWZXJzaW9uaW5nyBtBxFkuQ29yZTsKCkBzZXJ2aWNlKHsKICB0aXRsZTogIkRldkJveCIKfSkKQHVzZURlcGVuZGVuY3koyjzIWXMudjFfMF9QcmV2aWV3XzIpCm5hbWVzcGFjZSDGSMRmcmVzb3VyY2UoInByb2plY3RzIikKbW9kZWwgUMYRIOQAgUBrZXkgQHZpc2liaWxpdHkoInJlYWQiKQogIMc4TmFtZTogc3Ry5QDRCiAgb3RoZXJTdHVmZsoXfc1ydXNlcsRvQHBhcmVudFLIGcd56ACIVXNlcv8AhSDES0lk%2FwCA8ACAYm94037Eb8h75gEo330gZMUm8QEB1i34AS%2FWLuQA2P8A1uUA1m9wIGNyZWF0ZecAsmlzIOgA0UPFGE9yUmVwbGFjZTzGIj47Cg%3D%3D&e=%40azure-tools%2Ftypespec-autorest&options=%7B%7D
