### ISSUE TITLE
gRPC / protobuf considerations

### ISSUE THREAD

**Issue by mgravell** [microsoft/typespec#248]
The documentation repeatedly mentions gRPC, although I don't see any existing implementations, so I'm guessing this is a hypothetical at this point, with most of the focus on openapi/openapi3; I want to highlight that gRPC may have some additional implications that may need consideration. In particular, when talking about gRPC, we're usually (although not exclusively) talking about protobuf, which is an ordinal, not nominal, data format. To reliably be able to discuss protobuf models (without them breaking whenever there's any change to the schema), a way is required to nail down the ordinals very robustly. Failure to consider this promptly may significantly hamper any attempts to shoehorn gRPC into cadl at a later date.

I'd be happy to help discuss any relevant topics here; let me know if I can assist

(for context; I'm MSFT FTE in APIM, with extensive protobuf and gRPC knowledge)

**Comment by bterlson** [comment]
The sketches we have require a `@fieldnum` decorator on every model property in order to emit a model to protobuf. In a context where a model is used in both grpc and rest, this should be fine as the fieldnum will simply be ignored by the OA3 emitter.

It would be great to discuss this at some point! I think right now we are laser focused on nearer-term deliverables but... in the meantime, any other pitfalls we should watch out for?

**Comment by witemple-msft** [comment]
@mgravell I'm going to close this old issue since we've had `@typespec/protobuf` for some time now. If there are additional considerations that the current protobuf emitter does not address and are not covered by open issues tagged with the gRPC label, then we can track the specifics in separate issues.
