### ISSUE TITLE
Allow enums in `@visibility` decorator

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2514]
[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=ZW51bSBWaXNpIHsKICByZWFkLAp9CgoKbW9kZWwgRm9vxRhAdmlzaWJpbGl0eSjELS7EKSkKICBwcm9wOiBzdHJpbmc7Cn0%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

Things to think about:
- what to we do with existing string value(deprecate?)
- change the api to use union? `@visibility(HttpVis.read | HttpVis.write)`
- multiple `@visibility` does it append or override: We definitly need some appending functionality so you can provide visibiity foir different protocol but not being able to override might be limiting.

**Comment by qiaozha** [comment]
Not sure if we can use this issue to share all the visbility related feature requirements, here's some requirements from previous discussion.

- visibility should use an enumerated type rather than a string (for both model and operation visibility decorators
`@visibility`
`@parameterVisibility`
`@returnTypeVisibility`
`@withVisibility`
`@withDefaultKeyVisibility`
 including the future planning of visibility and optionality combination https://github.com/Azure/typespec-azure/issues/1117 [in fact, everywhere that visibility is used]) 

- TypeSpec should provide helpers to transform visibility into the information that emitters need when they are creating client models and serializing and deserializing operation requests and responses

- Provide a mechanism for specifying the names of models transformed by visibility
Proposal: to extend the `@clientName` decorator to support Visibility rename 
  ```
  @@clientName(ModelVisibility, "typescript", "ModelVisibilityCreateParameters", HttpVis.Create | HttpVis.Update)
  ```


Here's a unresolved topic from dotnet and java codegen side, which I haven't thought of a better proposal for it.  

- How to avoid cascade splitting models
   In the case that when one model has a deep nested model layers, it doesn't quite make sense if we just add visibility for one properties in a small properties. however we have to split all the models involved to the request body. [see the playground link](
https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCm1vZGVsIMcyxEVAdmlzaWJpbGl0eSgicmVhZCIsICJ1cGRhdGUiKSAKICBpZDogc3RyaW5nOwoKICB3ZWlnaHQ6IGludDMyOwogIGNvbG9yOiAicmVkIiB8ICJibHVlIjsKfchsymBNxRDEdXByb3A65wCGMsssxhIx0STQIjLRIjHEIwpAZXJyb3LHK0XEDMUpY29kZesAsm1lc3NhZ2XqANd9CgpAcm91dGUoIi93xU9zIikKQHRhZyjnAV3EEGludGVyZuQBU8cUxVxAcG9zdCBjcmVhdGUoQGJvZHkgxAU68AD4KdESIHzmAKPkAIA%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D) ( we can comment out the line 10 for visibility change to see the change.)

**Comment by witemple-msft** [comment]
Completed
