### ISSUE TITLE
OpenAPI applies read visibility to unreachable types

### ISSUE THREAD

**Issue by mikekistler** [microsoft/typespec#2517]
The docs for `@withVisibility` show this example
```
model Dog {
  @visibility("read") id: int32;
  @visibility("create", "update") secretName: string;
  name: string;
}

// The spread operator will copy all the properties of Dog into DogRead,
// and @withVisibility will then remove those that are not visible with
// create or update visibility.
//
// In this case, the id property is removed, and the name and secretName
// properties are kept.
@withVisibility("create", "update")
model DogCreateOrUpdate {
  ...Dog;
}
```

but the actual behavior as shown in the playground does not match the description in the doc.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKbW9kZWwgRG9nIHsKICBAdmlzaWJpbGl0eSgicmVhZCIpIGlkOiBpbnQzMjvQIWNyZWF0ZSIpIHNlY3JldE5hbWU6IHN0cmluZ8Qsbs0QfQoKLy8gVGhlIHNwxFogb3BlcmF0b3Igd2lsbCBjb3B5IGFsbCB0aGUgcHLEHXRpZXMgb2blAJ1pbnRvxAlSZWFkLMRJYW5kIEB3aXRoVukAkcZJdGhlbiByZW1vdmUgdGhvc8QGYXQgYXJlIG5vdCDlAMBsZSDEO8RI5gDEIG9yIHVwZMQK6gDhLgovL8QjSW4gdGhpcyBjYXNlLMRgIGlk6ACjeSBpc8duZCzlAJXEIOQA%2BsUN6gEZxEnrANfkAI9rZXB0LgrvAMXqAVbqAZtDxRJPclXmAKLkAakuLi5Eb%2BUBVg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

Note that `secretName` does not appear in either `Dog` or `DogCreateOrUpdate`.

**Comment by bterlson** [comment]
I believe the root cause in this particular case is that we are applying read visibility to models that aren't used in an operation.

```
import "@typespec/http";

using TypeSpec.Http;

model DogCreateOrUpdate {
  @visibility("read") id: int32;
  @visibility("create") secretName: string;
}
```
[Playground](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwoKbW9kZWwgRG9nQ3JlYXRlT3JVcGRhdGUgewogIEB2aXNpYmlsaXR5KCJyZWFkIikgaWQ6IGludDMyO9AhY8VBIikgc2VjcmV0TmFtZTogc3RyaW5nOwp9Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

I would expect both fields to be present in this case.

**Comment by timotheeguerin** [comment]
Keeping this issue for fixing `withVisibilities` and opened a new one about openapi3 handling of unreachable types #2571
