### ISSUE TITLE
  @visibility("create") has no effect

### ISSUE THREAD

**Issue by rdelmont** [microsoft/typespec#2604]
Property using @visibility("create") are not exported in any model.

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdCI7CgpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN0OwoKbW9kZWwgx13EcEBrZXkgaWQ6IHN0cmluZzvEE3Zpc2liaWxpdHkoInJlYWQiKSBwcm9wU2hvdWxkQmVJbkdFVDogaW50MzLRMGNyZWF0ZdEyUE9T2TN1cGTVM0FUQ0jLNMweRXZlcnl3aGVyZckhfQoKQGVycm9y5wDkRcQM5QDjY29kyicgIG1lc3NhZ2XqAPJ9CgppbnRlcmbkAVrmARvnAVwgZXh0ZW5kcyBSZXNvdXJjZeQBR8UJT3BlcmF0aW9uczzGMizGcT4gewp9Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%22linterRuleSet%22%3A%7B%22extends%22%3A%5B%22%40typespec%2Fhttp%2Fall%22%5D%7D%7D)

**Comment by markcowl** [comment]
- look at why this occurs
- potentially deprecate the interface template

**Comment by tjprescott** [comment]
@markcowl the issue here is the `ResourceCreateModel` template. It looks like this:
```
model ResourceCreateModel<TResource extends {}>
  is UpdateableProperties<DefaultKeyVisibility<TResource, "read">>;
```

Ultimately, this ends up filtering out properties that don't have "update" visibility.

Arguably, and this would be a breaking (fixing) change, we should have a `CreateableProperties` template and a `@withCreateableProperties` decorator, which would fix this.

It seems we erroneously assumed in the past that any properties on the update were the same for create, which given the visibility system, doesn't hold.
