### ISSUE TITLE
Should `T | never` be equivalent to optional property

### ISSUE THREAD

**Issue by timotheeguerin** [microsoft/typespec#2671]
```tsp
model Bar {
  b: int32 | never;
}
```

[Playground Link](https://cadlplayground.z22.web.core.windows.net/?c=bW9kZWwgQmFyIHsKICBiOiBpbnQzMiB8IG5ldmVyOwp9Cg%3D%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by timotheeguerin** [comment]
Templates where you have 

```
model Foo<T> {
  prop: T;
}
```
so you can from the value of `T` also make `prop` optional.

**Comment by markcowl** [comment]
It feels like you should never have to use `type | never` because never is a bottom type, it is always assignable to any other type.

We are getting increasing calls for being able to change the optionality of a property, particularly in instantiated operation templates.  We *may* need to provide a decorator for setting optionality.  We might also consider an optionality setting similar to '@visibility', that is conditional based on usage.

**Comment by markcowl** [comment]
@timotheeguerin - please delineate the parts of never /. void behavior we need to specity and document
