### ISSUE TITLE
[Bug] OpenApi3 emitter does not handle @returnTypeVisibility correctly

### ISSUE THREAD

**Issue by qiaozha** [microsoft/typespec#3032]
Currently OpenAPI3 emitter have only handled visibility read for response model in OpenAPI3 emitter, but we have `@returnTypeVisibility` to allow customers to have special visibilities for it which is not working. 
```
@returnTypeVisibility("read", "update")
@put op putModel(@body input: VisibilityModel): VisibilityModel;
```
Here's the emitter output
```
    put:
      operationId: putModel
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VisibilityModel'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VisibilityModelCreateOrUpdate'
```
Where the `VisibilityModel` only contains the readable properties.  Here's the [playground link](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7CtIZcmVzdCI7CgpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCnVzaW5nIFR5cGVTcGVjLkh0dHA70BVSZXN0OwoKbW9kZWwgVmlzaWJpbGl0eU3FEMR5QHbJFSgicmVhZCIpCiAgxAlQcm9wOiBzdHJpbmc7CtArcXVlcnnFLMUKxi1pbnQzMtIsY3JlYXRlxS3GC8xbW13SMXVwZMgxxgvLX9QwZGVsZccwxgvGMGJvb2xlYW47Cn0KCkByZXR1cm7kARnqAQfnAPIsIMpyQHB1dCBvcCBwdXTlASUoQGJvZHkgaW5wdXQ68AFCKdESOwoK&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by tjprescott** [comment]
I don't think this is a bug, because neither OpenAPI or Autorest emitters do anything with `@returnTypeVisibility`. This was because those emitters don't apply any kind of default visibility to their return types so there is no existing logic for the decorator to hook into. 

@markcowl I would recommend we reclassify this as feature work and give it a proper estimate. If there's any uncertainty as to the desired behavior, some design discussion might be warranted. 

Also, I think this will be addressed as part of the following issue:
https://github.com/microsoft/typespec/issues/3012

**Comment by markcowl** [comment]
Tracking in https://github.com/microsoft/typespec/issues/3012
