### ISSUE TITLE
unexpected Duplicate type name error on 0.54.0 of compiler 

### ISSUE THREAD

**Issue by DMaro28** [microsoft/typespec#3048]
Hi Team! I'm migrating my codebase from v0.48.1 of compiler to 0.54.0 and I have trouble with 
unexpected error @typespec/openapi/duplicate-type-name Duplicate type name. 

The structure is Model1 extends BaseModel and is used as a type in another model. This compiled fine in v0.48.1

Playground example is [here](https://cadlplayground.z22.web.core.windows.net/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCm1vZGVsIEJhc2VNxArER3Byb3BlcnR5MSA6IHN0cmluZwp9yCnGW0RlZmluaXRpb24gZXh0ZW5kc8xCLy8g1y1pzSgKICBhZGTFGmFsyHXYcyDkAJpAdmlzaWJpbGl0eSgicmVhZCIsICJ1cGRhdGUiKcQgcGF0aAogIGlkyEc7CiAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUixSrvALE68QDD5ACXQGVycm9y5wCeRcQM5QCdY29kZctlbWVzc2FnZeoAicQ6cm91dGUoIi%2FGaXMiKQpAdGFnKOcBssQQaW50ZXJm5AGoxxTFXEDkAQJsaXN0KCnoAJRbXSB8xn7EbsUh5AESKOUBBOsBAskxzS9wb3N0IGNyZWF0ZSguLi7GItcrYXRjaCDmAWbfLEBkZWxldGUgxgf0AIt2b2lkzTLnARJ7aWR9L2FuYWx5emUiKecAoMcQ1EjGCcpKfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D) .

Please note that if you replace 'extends' with 'is' in line 13, code compiles fine. Code also compiles fine if I comment out line 40, patch endpoint. Is this expected behavior? Any suggestions on fixes if I need to keep the structure as it is (I need to use extends for code generation purposes)
Thanks for your help!

**Comment by timotheeguerin** [comment]
I think that might be the same problem as this issue https://github.com/microsoft/typespec/issues/2922

**Comment by timotheeguerin** [comment]
Seems like it is, fixed in the [playground of the  pr](https://cadlplayground.z22.web.core.windows.net/prs/3049/?c=aW1wb3J0ICJAdHlwZXNwZWMvaHR0cCI7Cgp1c2luZyBUeXBlU3BlYy5IdHRwOwpAc2VydmljZSh7CiAgdGl0bGU6ICJXaWRnZXQgU8YbIiwKfSkKbmFtZXNwYWNlIERlbW%2FHGzsKCm1vZGVsIEJhc2VNxArER3Byb3BlcnR5MSA6IHN0cmluZwp9yCnGW0RlZmluaXRpb24gZXh0ZW5kc8xCLy8g1y1pzSgKICBhZGTFGmFsyHXYcyDkAJpAdmlzaWJpbGl0eSgicmVhZCIsICJ1cGRhdGUiKcQgcGF0aAogIGlkyEc7CiAgd2VpZ2h0OiBpbnQzMsQRY29sb3I6ICJyZWQiIHwgImJsdWUixSrvALE68QDD5ACXQGVycm9y5wCeRcQM5QCdY29kZctlbWVzc2FnZeoAicQ6cm91dGUoIi%2FGaXMiKQpAdGFnKOcBssQQaW50ZXJm5AGoxxTFXEDkAQJsaXN0KCnoAJRbXSB8xn7EbsUh5AESKOUBBOsBAskxzS9wb3N0IGNyZWF0ZSguLi7GItcrYXRjaCDmAWbfLEBkZWxldGUgxgf0AIt2b2lkzTLnARJ7aWR9L2FuYWx5emUiKecAoMcQ1EjGCcpKfQo%3D&e=%40typespec%2Fopenapi3&options=%7B%7D)

**Comment by DMaro28** [comment]
Thank you @timotheeguerin , @bterlson for the quick turnaround on this
