### ISSUE TITLE
highlight #suppression for better suppression identification

### ISSUE THREAD

**Issue by allenjzhang** [microsoft/typespec#3349]
### Clear and concise description of the problem

It would be nice to highlight `#suppression` line in editors for better identification when viewing.

### Checklist

- [X] Follow our [Code of Conduct](https://github.com/microsoft/typespec/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://typespec.io/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by markcowl** [comment]
Priority: 1

**Comment by RodgeFu** [comment]
@timotheeguerin , I can't find a proper SemanticToken or scope in vscode for the highlight. do you have any suggestions? thanks.

**Comment by RodgeFu** [comment]
Agree that from vs/vscode extension perspective, if user adds the ```suppress``` explicitly, he would expect the item to be ignored instead of highlighted. Also in c#, the ```#pragma warning disable ...``` or ```[SuppressMessage(...)]``` are both greyed out. so close the issue.

@allenjzhang , feel free to reopen if you still want them to be highlighted in vs/vscode extension for some reason. thanks.
