### ISSUE TITLE
Add support to generate a model as struct instead of class in csharp

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#3453]
We need to support the ability of generating structs for models in csharp.

**Comment by ShivangiReja** [comment]
Discussed Offline: We will add a `@@modelAsStruct` decorator to the C# emitter to enable the generation of a model as a struct instead of a class.

We will use this issue to track the C# generation in the generator. Here’s the issue [#3619](https://github.com/microsoft/typespec/issues/3619) to add the decorator in the emitter.
