### ISSUE TITLE
`output-dir` vs `project-dir`

### ISSUE THREAD

**Issue by ArcturusZhang** [microsoft/typespec#4283]
I think the value of `output-dir` and `project-dir` are kind of reversed
```csharp
        internal string OutputDirectory { get; }

        private string? _projectDirectory;
        internal string ProjectDirectory => _projectDirectory ??= Path.Combine(OutputDirectory, "src");
```
The `output-dir` should be: `{project-root}/src/Generated`
and the `project-dir` should be `{project-root}/src` or `{project-root}`

but looks like it is reversed.

**Comment by m-nash** [comment]
I think it depends on what you think you are "outputing".  Since the `Library.sln` file is part of the "output" what directory does that go into?

"output-dir" should be whatever the compiler gave us for emitter-output-dir which defaults to output-dir if not overridden on input.

The project dir is that plus src since that is where the project (csproj for the library) goes.

I think that autorest-csharp has this backwards and mgc has it correct unless I am missing something.

**Comment by ArcturusZhang** [comment]
OK if it is by-design, I am fine with it. I managed to get it straight in my PR as well therefore if this is by design, it is fine.
Let me close this.
