### ISSUE TITLE
Support Customizing Discriminator Type as Fixed Enum

### ISSUE THREAD

**Issue by chunyu3** [microsoft/typespec#4313]
In some scenario(e.g. customize the property type), we may need to get some information from `TypeProvider` of a `CSharpType`, e.g. the `EnumValues` of an Enum type;
 
possible scenario: when we customize the discriminator type in customized code(e.g. change the discriminator type to an enum from string), we may need to know the `EnumValues` to construct the member value. So we need a way to get `TypeProvider` for this `CSharpType`.
 Maybe we can record a map <CSharpType, TypeProvider>, then we will retrieve the TypeProvider via CSharpType, and then we can get the EnumValues from TypeProvider.

**Comment by jorgerangel-msft** [comment]
More details about the problem: 
There can be a scenario where a user customizes a discriminator property's type in a model via customized code. Specifically, if the original discriminator spec type is a primitive, and it is customized to a custom enum, the generator will generate the property using the custom enum type, as expected. The problem occurs when we try to construct the discriminator value to be used in the derived model's constructors for this model, as we'll need to create the value expression for the discriminator property to pass to the base constructor using the custom enum type and **not** the type from spec. Here is an example of this scenario:

### Custom code
```c#
public partial class ChatMessage
{    
    // CUSTOM: Changed type from string to ChatMessageRole.
    [CodeGenMember("Role")]
    internal ChatMessageRole Role { get; set; }
}

[CodeGenModel("ChatCompletionRole")]
public enum ChatMessageRole
{
    [CodeGenMember("System")]
    System,
}
```

### Current Generated Code (derived model)
```c#
   public abstract partial class ChatMessage
    {
        private protected IDictionary<string, BinaryData> _additionalBinaryDataProperties;
        private protected ChatMessage(ChatMessageRole role)
        {
            Role = role;
        }
    
        // serialization ctor
    }


    public partial class SystemChatMessage : ChatMessage
    {
        public SystemChatMessage() : base("system")
        {
        }

        // serialization ctor ...
    }

```

For the `SystemChatMessage` primary ctor, the call to the base model's ctor should use the custom type to construct the discriminator value, `ChatMessageRole.System`, rather than the original type from the spec. We will need a way to get this information when constructing the discriminator's value.
