### ISSUE TITLE
Parameters docs with newline char are not generated correctly

### ISSUE THREAD

**Issue by JoshLove-msft** [microsoft/typespec#4377]
For parameters that have descriptions containing a newline char, subsequent lines are missing the leading `///`:

![image](https://github.com/user-attachments/assets/6e9144bc-b296-451f-b780-d75a51409e18)

**Comment by nisha-bhatia** [comment]
Ideally, we would like to update the [EscapeLines ](https://github.com/microsoft/typespec/blob/main/packages/http-client-csharp/generator/Microsoft.Generator.CSharp/src/Statements/XmlDocStatement.cs#L36) method here to take \n into account. Unfortunately, this is proving to be difficult. We cannot use .ToString(). Updating the code as so:
![Image](https://github.com/user-attachments/assets/5d80bbc2-6cb9-49cc-8225-c910df05f142)
We could have multiple arguments in each \n segment, leading to a recursive solution. We can also have an Object in a FormattableString? We can't call .ToString() on every object because this method might be overloaded. 

I believe it's easier to update the WriteLines methods to just print "\\\" whenever we see a line break, but then we are manipulating the data in multiple places.
