### ISSUE TITLE
Where to import Lifecycle, Create, etc. from? (docs issue)

### ISSUE THREAD

**Issue by markandrus** [microsoft/typespec#5325]
Docs mention using `@visibility(Lifecycle.Read)`, but where can I import `Lifecycle.Read` from? Or is this deprecated in favor of just `@visibility("read")`? How about type templates like `Create<T>`?

**Comment by markcowl** [comment]
LifecycleVisibility is part of the typespec core library, there is no need to import it.

**Comment by witemple-msft** [comment]
`Lifecycle` is defined in the TypeSpec namespace. You don't have to import it or use a `using`. It is available by default in every namespace because the compiler treats every namespace as if it is `using TypeSpec;`. I'm not completely sure which version of TypeSpec this was added in, but it was within the last couple of months. If you find it's not available you may need to update TypeSpec for it to become available.

> is this deprecated in favor of just @visibility("read")

It's the other way around. The string forms of visibility will be deprecated in the future in favor of enums like `Lifecycle`.

> How about type templates like Create<T>

The templates are also defined in the TypeSpec namespace, and are available in all namespaces. You can just say `Create<Foo>` and the template will produce a copy of `Foo` with only properties that have `Lifecycle.Create` visibility. It is backwards compatible, so it recognizes `"create"` as equivalent to `Lifecycle.Create`, but in the future we will likely deprecate the string version with a warning.

**Comment by witemple-msft** [comment]
@markandrus I'm going to close this, but if you think there's something for us to do or have any other questions please feel free to reopen the issue or file a separate one. Thanks!

**Comment by markandrus** [comment]
Thanks, y'all! I confirm I see these in the typespec Playground, so I think I had an older version of typespec installed locally.
