### ISSUE TITLE
Well defined versioning rules

### ISSUE THREAD

**Issue by markweitzel** [microsoft/typespec#907]
Define, document, and implement how Cadl supports versioning of decorators, models, and libraries; how this impacts artifact generation (code, docs, open api docs) etc.

**Comment by allenjzhang** [comment]
We have a work item on our library versioning documentation. Because of project.json is able to key onto a specific version, there shouldn't be any impact. We can document @deprecation and its error messages so that when a user upgrades library version, they can take appropriate actions to upgrade deprecated items.

**Comment by allenjzhang** [comment]
What I mentioned above is around Cadl package versioning. There is another aspect of Cadl spec versioning. Cadl has inbuilt versioning support via `@cadl-lang/versioning` package. These cover how spec-versioning is handled such as the evolution of service models and service interfaces. Our standard libraries (ARM, Azure.Core) already takes advantage of this to cover the common models defined in the library to avoid breaking changes for user specs down the road. There are small gaps and corner cases we are ironing out which should be completed by Zinc.

**Comment by allenjzhang** [comment]
I think at this point this is a documentation exercise for versioning related stuff and FAQ/examples.
